flight_test <-read.csv(file.choose(), header = T , sep = ",")
dim(flight_test)
head(flight_test)
library(dplyr)
filter_table <- select(flight_test , DAY_OF_MONTH , DAY_OF_WEEK ,DEP_DELAY_NEW ,ARR_DELAY_NEW ,CARRIER_DELAY ,WEATHER_DELAY, NAS_DELAY , SECURITY_DELAY , LATE_AIRCRAFT_DELAY)
tail(filter_table)
filter_table <- select(flight_test , DEP_DEL15 , ARR_DEL15)
tail(filter_table)
filter_table <- select(flight_test , DEP_DEL15 ,DEP_DELAY_NEW, ARR_DEL15 , ARR_DELAY_NEW ,CARRIER_DELAY , WEATHER_DELAY , NAS_DELAY , SECURITY_DELAY , LATE_AIRCRAFT_DELAY)
tail(filter_table)
logit_reg_5factors <- glm(DEP_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + NAS_DELAY +SECURITY_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
summary(logit_reg_5factors)
confint(logit_reg_5factors)
plot.lm()
plot(logit_reg_5factors)
log_reg_4factors <- glm(DEP_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + NAS_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
summary(log_reg_4factors)
summary(log_reg_4factors)
log_4factors <- glm(DEP_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + NAS_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
summary(log_4factors)
log_3factors <- glm(DEP_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
summary(log_3factors)
confint(log_3factors)
log_3diff <-  glm(DEP_DEL15 ~ CARRIER_DELAY + NAS_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
log_3diff <-  glm(DEP_DEL15 ~ CARRIER_DELAY + NAS_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
summary(log_3diff)
confint(log_3diff)
plot(log_3diff)

plot(log_3factors)
plot(log_4factors)
plot(logit_reg_5factors)
log_2fac <- glm(DEP_DEL15 ~ CARRIER_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
summary(log_2fac)
confint(log_2fac)
plot(log_2fac)
tail(filter_table)
log_arr5fact <- glm(ARR_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + NAS_DELAY +SECURITY_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
log_arr4fact <- glm(ARR_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + NAS_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
log_arr3fact <- glm(ARR_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
log_arr2fact <- glm(ARR_DEL15 ~ CARRIER_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
summary(log_arr2fact)
confint(log_arr2fact)
summary(log_arr3fact)
confint(log_arr3fact)
plot(log_arr3fact)
summary(log_arr4fact)
confint(log_arr4fact)
plot(log_arr4fact)
summary(log_arr5fact)
confint(log_arr5fact)
plot(log_arr5fact)
log_arr5 <- glm(ARR_DEL15 ~ CARRIER_DELAY + WEATHER_DELAY + NAS_DELAY +SECURITY_DELAY + LATE_AIRCRAFT_DELAY , data = filter_table , family = "binomial")
plot(log_arr5)
